# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [177]:
import numpy as np    # importing the Numpy library as np 




### 2. Print the NUMPY version and the configuration.


In [178]:
print(np.__version__); np.show_config()      # printing Numpy version and configuration

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ASUS/anaconda3/Library/include
    lib directory: C:/Users/ASUS/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ASUS/anaconda3/Library/include
    lib directory: C:/Users/ASUS/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
    vers

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [179]:
x, y, z = 2, 3, 5    # number of dimensions in this array's case

a = np.random.rand(x, y, z)


In [180]:
array_alt1 = np.random.random((x, y, z))    # accepts a tuple
array_alt1

array([[[0.20685472, 0.2837363 , 0.22700892, 0.35674216, 0.16226604],
        [0.12074601, 0.7445652 , 0.89731427, 0.14505879, 0.92304788],
        [0.56691566, 0.70994734, 0.08575455, 0.4075635 , 0.98207964]],

       [[0.11628085, 0.37233877, 0.88412823, 0.02837357, 0.05115718],
        [0.68602952, 0.56126466, 0.37755479, 0.94439905, 0.13555331],
        [0.08467268, 0.4657756 , 0.84594537, 0.08216264, 0.75895798]]])

In [181]:
rng = np.random.default_rng()      # using a random generator API, for more reliable randomness
array_alt2 = rng.random((x, y, z))
array_alt2

array([[[0.47029224, 0.99035158, 0.26013486, 0.88644462, 0.18515953],
        [0.06038704, 0.66895126, 0.29261322, 0.90665847, 0.46937773],
        [0.41564381, 0.85644623, 0.23501421, 0.64319716, 0.97284708]],

       [[0.54972867, 0.96284948, 0.4133659 , 0.0016472 , 0.92046954],
        [0.48887192, 0.17089456, 0.14256663, 0.1888004 , 0.97369509],
        [0.3162935 , 0.04485072, 0.8303505 , 0.75863458, 0.23339764]]])

In [182]:
array_alt3 = np.random.randn(x, y, z)    # normally distributed random values
array_alt3

array([[[-0.63650606, -2.54644252,  0.41640177, -1.6897412 ,
          1.12297801],
        [-0.38039145,  0.24825787,  0.49582477,  1.4614921 ,
         -0.44176625],
        [ 0.5501549 , -1.16754184, -0.73822233,  0.69391905,
          0.29493505]],

       [[ 0.02626601, -0.48515844, -1.42803354,  1.41034856,
         -0.66883636],
        [-0.03864363,  1.04315366, -0.11310168, -0.15753216,
          0.42959601],
        [-0.57729982, -0.09632668, -1.98626374,  0.06899022,
          1.66604662]]])

In [183]:
array_alt4 = np.random.randint(0, 10, size=(x, y, z))   # generating random integer values between 0 and 9
array_alt4

array([[[4, 8, 2, 4, 8],
        [0, 9, 9, 5, 7],
        [4, 2, 0, 7, 1]],

       [[4, 6, 8, 8, 2],
        [0, 4, 1, 7, 6],
        [9, 6, 5, 2, 0]]], dtype=int32)


### 4. Print a.


In [184]:
a

array([[[0.42031825, 0.92417723, 0.69763774, 0.5616411 , 0.84750012],
        [0.55460066, 0.70233351, 0.85399188, 0.29635947, 0.3379649 ],
        [0.46123569, 0.06987123, 0.40263073, 0.96675033, 0.51255132]],

       [[0.02688094, 0.86537671, 0.89648403, 0.64307013, 0.93468011],
        [0.90278615, 0.56701985, 0.20934077, 0.28790497, 0.54714806],
        [0.95055328, 0.33102774, 0.32488908, 0.32802333, 0.73195387]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [185]:
m, n, o = 5, 2, 3

b = np.ones((m, n, o))



### 6. Print b.


In [186]:
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [187]:
print(a.size) # 30 elements
print(b.size)   # also 30 elements

# In boolean terms, we can compare both arrays' sizes as follows:

print(a.size == b.size)     # a and b are, in fact, of the same size


30
30
True



### 8. Are you able to add a and b? Why or why not?


In [188]:
print(a.shape == b.shape);    # incompatibility due to shapes of a and b being different; hence, cannot add these two arrays

# In fact: 

if a.shape == b.shape:
    sum_arrays = a + b
else:
    print("Shapes of arrays are not compatible.")


False
Shapes of arrays are not compatible.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [189]:
# c = b.T    - this would not have worked because axes would have been reversed

# Need a.shape = (2, 3, 5) = Transpose b = c.

# Note that .T transposes axes. This one works ok in 2D arrays. For more dimensions, need to use "transpose" function.

# Therefore:

c = np.transpose(b, (1, 2, 0))     # to force elements of b being presented in a compatible manner for addition

print(a.shape == c.shape)    # shapes now match


True



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [190]:
print(a.shape == c.shape);    # compatibility of shapes of a and c; hence, can add these two arrays

# In fact: 

if a.shape == c.shape:
    d = a + c
    print("Can add arrays.")
else:
    print("Shapes of arrays are not compatible.")


True
Can add arrays.



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [191]:
print(a)
print(d)

# We notice that the difference between a's elements and b's elements is 1. Hence:

# b = a + 1



[[[0.42031825 0.92417723 0.69763774 0.5616411  0.84750012]
  [0.55460066 0.70233351 0.85399188 0.29635947 0.3379649 ]
  [0.46123569 0.06987123 0.40263073 0.96675033 0.51255132]]

 [[0.02688094 0.86537671 0.89648403 0.64307013 0.93468011]
  [0.90278615 0.56701985 0.20934077 0.28790497 0.54714806]
  [0.95055328 0.33102774 0.32488908 0.32802333 0.73195387]]]
[[[1.42031825 1.92417723 1.69763774 1.5616411  1.84750012]
  [1.55460066 1.70233351 1.85399188 1.29635947 1.3379649 ]
  [1.46123569 1.06987123 1.40263073 1.96675033 1.51255132]]

 [[1.02688094 1.86537671 1.89648403 1.64307013 1.93468011]
  [1.90278615 1.56701985 1.20934077 1.28790497 1.54714806]
  [1.95055328 1.33102774 1.32488908 1.32802333 1.73195387]]]



### 12. Multiply a and c. Assign the result to e.


In [192]:
e = a*c
e


array([[[0.42031825, 0.92417723, 0.69763774, 0.5616411 , 0.84750012],
        [0.55460066, 0.70233351, 0.85399188, 0.29635947, 0.3379649 ],
        [0.46123569, 0.06987123, 0.40263073, 0.96675033, 0.51255132]],

       [[0.02688094, 0.86537671, 0.89648403, 0.64307013, 0.93468011],
        [0.90278615, 0.56701985, 0.20934077, 0.28790497, 0.54714806],
        [0.95055328, 0.33102774, 0.32488908, 0.32802333, 0.73195387]]])



### 13. Does e equal to a? Why or why not?


In [193]:
# print (a.shape == e.shape)

# print(a == e)

# a is in fact equal to e given that their shapes are equal and that there is a one to one correspondence between each and every one of their values

# By accessing array_equal function of Numpy:

np.array_equal(a, e)



True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [194]:
d_max = np.max(d)    # accessing the max function of the Numpy library

d_min = np.min(d)   # accessing the min function of the Numpy library

d_mean = np.mean(d)    # accessing the mean function of the Numpy library

print(d_max)
print(d_min)
print(d_mean)



1.9667503307230754
1.026880937203301
1.5718901054340586



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [195]:
f = np.empty((d.shape))    # to ensure we get an empty array with the same shape as d





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [196]:
f[(d > d_min) & (d < d_mean)] = 25     # element-wise logic (not single booleans), hence the &

f[(d > d_mean) & (d < d_max)] = 75

f[(d == d_mean)] = 50

f[d == d_min] = 0

f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [197]:
print(d)
print(f)    # must follow all conditions enforced above


[[[1.42031825 1.92417723 1.69763774 1.5616411  1.84750012]
  [1.55460066 1.70233351 1.85399188 1.29635947 1.3379649 ]
  [1.46123569 1.06987123 1.40263073 1.96675033 1.51255132]]

 [[1.02688094 1.86537671 1.89648403 1.64307013 1.93468011]
  [1.90278615 1.56701985 1.20934077 1.28790497 1.54714806]
  [1.95055328 1.33102774 1.32488908 1.32802333 1.73195387]]]
[[[ 25.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  25. 100.  25.]]

 [[  0.  75.  75.  75.  75.]
  [ 75.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [198]:
h = np.empty(d.shape, dtype = object)    # forcing use of a string data type

h[(d > d_min) & (d < d_mean)] = "B"     # element-wise logic (not single booleans), hence the &

h[(d > d_mean) & (d < d_max)] = "D"

h[(d == d_mean)] = "C"

h[d == d_min] = "A"

h[d == d_max] = "E"

h

array([[['B', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'E', 'B']],

       [['A', 'D', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'B', 'D']]], dtype=object)

In [200]:
# Using a for loop:

alternative_array = np.empty(d.shape, dtype = object)    # forcing use of a string data type

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):

            if d[i, j, k] == d_min:
                alternative_array[i, j, k] = "A"
            elif d[i, j, k] < d_mean:
                alternative_array[i, j, k] = "B"
            elif d[i, j, k] == d_mean:
                alternative_array[i, j, k] = "C"
            elif d[i, j, k] < d_max:
                alternative_array[i, j, k] = "D"
            else:
                alternative_array[i, j, k] = "E"

alternative_array



array([[['B', 'D', 'D', 'B', 'D'],
        ['B', 'D', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'E', 'B']],

       [['A', 'D', 'D', 'D', 'D'],
        ['D', 'B', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'B', 'D']]], dtype=object)