# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [31]:
import numpy as np    # importing the Numpy library as np 




### 2. Print the NUMPY version and the configuration.


In [32]:
print(np.__version__); np.show_config()      # printing Numpy version and configuration

2.3.5
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ASUS/anaconda3/Library/include
    lib directory: C:/Users/ASUS/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/ASUS/anaconda3/Library/include
    lib directory: C:/Users/ASUS/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython
    name: cython
    vers

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [33]:
x, y, z = 2, 3, 5    # number of dimensions in this array's case

a = np.random.rand(x, y, z)


In [34]:
array_alt1 = np.random.random((x, y, z))    # accepts a tuple
array_alt1

array([[[0.87341758, 0.15769891, 0.71021585, 0.39068747, 0.14029142],
        [0.34250816, 0.63091093, 0.86025031, 0.46939267, 0.01579039],
        [0.96141273, 0.78049044, 0.35567282, 0.78580041, 0.7131134 ]],

       [[0.68431252, 0.50050326, 0.89886054, 0.24119536, 0.48519312],
        [0.97659406, 0.20000686, 0.50035997, 0.2401865 , 0.95318502],
        [0.97245464, 0.94234928, 0.47979832, 0.35119568, 0.69747602]]])

In [35]:
rng = np.random.default_rng()      # using a random generator API, for more reliable randomness
array_alt2 = rng.random((x, y, z))
array_alt2

array([[[0.44273502, 0.53539401, 0.23395464, 0.29789477, 0.53389321],
        [0.77993141, 0.76313903, 0.19999498, 0.14708776, 0.07138087],
        [0.30201034, 0.3432415 , 0.52204446, 0.34704564, 0.78415885]],

       [[0.4085523 , 0.85210867, 0.88983351, 0.8358396 , 0.44165611],
        [0.71323429, 0.35719706, 0.69873709, 0.47863039, 0.61829913],
        [0.41470174, 0.47842499, 0.37427501, 0.87964561, 0.88210811]]])

In [36]:
array_alt3 = np.random.randn(x, y, z)    # normally distributed random values
array_alt3

array([[[-2.15831121,  0.45955996,  0.67147151,  0.01172028,
         -0.24328188],
        [ 1.33475908, -0.16906432,  0.8152156 , -1.03931893,
          0.85013598],
        [-0.08747252,  0.887179  , -1.31715388, -2.41456242,
         -2.02948001]],

       [[-0.42189258, -0.00371426, -0.85637687, -0.90385614,
         -0.58984106],
        [ 0.65886281, -0.91198103,  0.37169513, -0.2453883 ,
         -1.52851418],
        [ 0.877715  , -0.00695026, -1.11471318, -0.63140319,
         -0.08671614]]])

In [37]:
array_alt4 = np.random.randint(0, 10, size=(x, y, z))   # generating random integer values between 0 and 9
array_alt4

array([[[3, 0, 4, 2, 8],
        [4, 8, 9, 5, 5],
        [2, 8, 6, 0, 8]],

       [[4, 6, 4, 6, 1],
        [5, 6, 0, 5, 4],
        [7, 3, 4, 5, 5]]], dtype=int32)


### 4. Print a.


In [38]:
a

array([[[0.6826027 , 0.93631828, 0.43927131, 0.91638107, 0.34587629],
        [0.6387388 , 0.41032289, 0.87073601, 0.38714338, 0.75411021],
        [0.37640449, 0.76736091, 0.67688675, 0.04728985, 0.72883016]],

       [[0.09233874, 0.67836505, 0.83224605, 0.4631994 , 0.36853939],
        [0.13756839, 0.94865635, 0.70479035, 0.13439862, 0.53270935],
        [0.7291832 , 0.61901141, 0.70241379, 0.05075933, 0.26532345]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [39]:
m, n, o = 5, 2, 3

b = np.ones((m, n, o))



### 6. Print b.


In [40]:
b


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
print(a.size) # 30 elements
print(b.size)   # also 30 elements

# In boolean terms, we can compare both arrays' sizes as follows:

print(a.size == b.size)     # a and b are, in fact, of the same size


30
30
True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
print(a.shape == b.shape);    # incompatibility due to shapes of a and b being different; hence, cannot add these two arrays


if a.shape == b.shape:
    c = a + b
else:
    print("Shapes of arrays are not compatible")


False
Shapes of arrays are not compatible




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [43]:
### [your code here]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [44]:
### [your code here]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [45]:
### [your code here]




### 12. Multiply a and c. Assign the result to e.


In [46]:
### [your code here]




### 13. Does e equal to a? Why or why not?


In [47]:
### [your code here]





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [48]:
### [your code here]




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [49]:
### [your code here]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [50]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [51]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [52]:
### [your code here]